 apiVersion: v1
 kind: Service
 metadata:
   name: bee
   labels:
     app: bee
 spec:
   type: ClusterIP
   ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
   selector:
     app: bee
